task:
  name: FreeBSD $FREEBSD_VERSION ($TOOLCHAIN)

  freebsd_instance:
    cpu: 1
    image_family: $FREEBSD_IMAGE

  matrix:
    - env:
        FREEBSD_VERSION: 12.2
        FREEBSD_IMAGE: freebsd-12-2
    - env:
        FREEBSD_VERSION: 12.2 STABLE
        FREEBSD_IMAGE: freebsd-12-2-snap
    # - env:
    #     FREEBSD_VERSION: 13.0
    #     FREEBSD_IMAGE: freebsd-13-0-snap

  matrix:
    - env:
        TOOLCHAIN: stable
    - env:
        TOOLCHAIN: beta
    - env:
        TOOLCHAIN: nightly

  env:
    CODECOV_TOKEN: ENCRYPTED[100d8c6f2026e5775bf09b651b6e24afc90e6f462ecb9aba60e5a18158da4f551f1c2b0380b7788d301a3623f6c70ad1]

  install_script:
    - pkg install -y curl kcov bash
    - curl -sSf https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile default --default-toolchain $TOOLCHAIN
  build_script:
    - . $HOME/.cargo/env
    - cargo build
  std_test_script:
    - . $HOME/.cargo/env
    - cargo clean
    - cargo test
    - |
      mkdir -p coverage-std
      for f in target/debug/deps/*; do
        if [ -x "$f" ]; then
          echo
          echo "=== $f ==="
          echo
          kcov --exclude-pattern=/.cargo,/.rustup,/usr/lib --verify coverage-std "$f"
        fi
      done
  alloc_test_script:
    - . $HOME/.cargo/env
    - cargo clean
    - cargo test --no-default-features --features alloc
    - |
      mkdir -p coverage-alloc
      for f in target/debug/deps/*; do
        if [ -x "$f" ]; then
          echo
          echo "=== $f ==="
          echo
          kcov --exclude-pattern=/.cargo,/.rustup,/usr/lib --verify coverage-alloc "$f"
        fi
      done
  no_std_test_script:
    - . $HOME/.cargo/env
    - cargo clean
    - cargo test --no-default-features
    - |
      mkdir -p coverage-no-std
      for f in target/debug/deps/*; do
        if [ -x "$f" ]; then
          echo
          echo "=== $f ==="
          echo
          kcov --exclude-pattern=/.cargo,/.rustup,/usr/lib --verify coverage-no-std "$f"
        fi
      done
  coverage_collect_upload_script:
    - kcov --merge coverage-merged/ coverage-std/ coverage-alloc/ coverage-no-std/
    - OS="$FREEBSD_IMAGE" bash <(curl -s https://codecov.io/bash) -e OS,TOOLCHAIN -n "$FREEBSD_IMAGE-$TOOLCHAIN" -Z -f coverage-merged/kcov-merged/cobertura.xml
